export const ROLES = {
  ADMIN: 'ADMIN',
  BASE_COMMANDER: 'BASE_COMMANDER',
  LOGISTIC_OFFICER: 'LOGISTIC_OFFICER',
};

export const TRANSACTION_TYPES = {
  PURCHASE: 'PURCHASE',
  TRANSFER_IN: 'TRANSFER_IN',
  TRANSFER_OUT: 'TRANSFER_OUT',
  ASSIGN: 'ASSIGN',
  EXPEND: 'EXPEND',
};
